### ISSUE TITLE
Create testnet specific AWS account

### ISSUE THREAD

**Issue by nopestack** [WalletConnect/wcn#15]
Create a testnet specific account to isolate and easily control irn-node deployments participating in the alpha permissioned IRN.

```[tasklist]
### Tasks
- [ ] Create AWS account
- [ ] Setup terraform to launch nodes in said account
- [ ] Verify nodes launched can be accessed publicly via the node CLI
```
